# Generated by Django 3.1.7 on 2021-12-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('img', models.ImageField(upload_to='media')),
                ('img1', models.ImageField(upload_to='media')),
                ('img2', models.ImageField(upload_to='media')),
                ('package_detail', models.CharField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roominfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='delux', max_length=250, unique=True)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Roomdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('img', models.ImageField(upload_to='media')),
                ('img1', models.ImageField(upload_to='media')),
                ('img2', models.ImageField(upload_to='media')),
                ('slug', models.SlugField(max_length=200)),
                ('capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_detail', models.CharField(max_length=10000)),
                ('published', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('is_booked', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roominfoapi.roominfo')),
            ],
        ),
    ]
